---
# tasks file for hostname
  - name: Coletando fatos
    set_fact:
      nome: "{{ ansible_hostname }}"
    register: name_result     

  - name: gravando saída
    set_stats:
      data: 
        resultado_nome: "{{ name_result.ansible_facts.nome }}"