---
# tasks file for hostname
  - name: Coletando fatos
    set_fact:
      nome: "{{ ansible_hostname }}"
    register: name_result

  - debug:
      var: name_result

  - name: gravando saída
    set_stats:
      data: 
        resultado_nome: "{{ name_result }}"
      per_host: yes